[package]
name = "polls"
version = "1.0.0"
authors = ["Antoni Simka <antonisimka.8@gmail.com>"]
edition = "2021"

[dependencies]
actix-files = "0.5.0"
actix-web = "3"
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.14"

askama = "0.10.0"
qstring = "0.7.2"
serde = { version = "1", features = ["derive"] }
bincode = "2.0.0-beta.3"
base64 = "0.13.0"
rand = "0.8.5"

r2d2 = "0.8"
r2d2_sqlite = "0.19"
rusqlite = "0.26"
chrono = "0.4.19"
