[package]
name = "polls"
version = "1.0.0"
authors = ["Antoni Simka <antonisimka.8@gmail.com>"]
edition = "2021"

[dependencies]
actix-files = "0.5.0"
actix-web = "3"
askama = "0.10.0"
env_logger = "0.9.0"
log = "0.4.14"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
actix-rt = "2.6.0"
