[package]
authors = ["Antoni Simka <antonisimka.8@gmail.com>"]
edition = "2021"
name = "polls"
version = "1.0.0"
[dependencies]
actix-files = "0.5.0"
actix-web = "3"
anyhow = "*"
askama = "0.10.0"
base64 = "0.13.0"
bincode = "2.0.0-beta.3"
chrono = "0.4.19"
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.14"
qstring = "0.7.2"
r2d2 = "0.8"
r2d2_sqlite = "0.19"
rand = "0.8.5"
rusqlite = "0.26"
thiserror = "*"

[dependencies.serde]
features = ["derive"]
version = "1"
